import { writeFile } from "node:fs/promises";
import { gzipSync } from "node:zlib";
import { buildKitchenWidgetResource } from "../src/mcp/build-widget";

async function main() {
  const outputUrl = new URL(
    "../src/mcp/kitchen-widget.generated.ts",
    import.meta.url,
  );
  const resource = await buildKitchenWidgetResource();
  const compressedHtml = gzipSync(resource.html, { level: 9 }).toString(
    "base64",
  );
  const source = [
    "// Generated by scripts/build-mcp-widget.ts. Do not edit by hand.",
    'import { gunzipSync } from "node:zlib";',
    "",
    `const compressedHtml = ${JSON.stringify(compressedHtml)};`,
    "export const kitchenWidgetResource = {",
    '  html: gunzipSync(Buffer.from(compressedHtml, "base64")).toString("utf8"),',
    `  uri: ${JSON.stringify(resource.uri)},`,
    "} as const;",
    "",
  ].join("\n");

  await writeFile(outputUrl, source, "utf8");
  console.log(`Built ${resource.uri}`);
}

void main();
